# Generated by Django 4.2.1 on 2023-06-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_publicacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto'),
        ),
    ]
