# Generated by Django 4.2.1 on 2023-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='producto_id',
            field=models.IntegerField(default=1),
        ),
    ]
