# Generated by Django 4.2.1 on 2023-06-25 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0007_alter_publicacion_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fechaComentario']},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_comentario',
            new_name='fechaComentario',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fechaPublicacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='imagen',
            new_name='imagenProducto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyecto.publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default='Valor predeterminado', max_length=40),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='emailContacto',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=40),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='modelo',
            field=models.CharField(default='pruba.jpg', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='producto',
            field=models.CharField(default='dafault', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='telefonoContacto',
            field=models.IntegerField(default='198198191'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='year',
            field=models.IntegerField(default='2022'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
