# Generated by Django 4.2.1 on 2023-06-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_delete_producto_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='producto',
            field=models.CharField(choices=[('consola', 'Consola'), ('Celular', 'Celular'), ('computadora', 'Computadora')], default='consola', max_length=15),
        ),
    ]
